name: Release

on:
  push:
    tags:
      - '*'
    branches:
      - master

env:
  REGISTRY: ghcr.io
  REGISTRY_DOCKERHUB: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-22.04
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Set output
        id: vars
        run: echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.x
      - name: Image Registry Login
        run: |
          docker login --username linuxsuren --password ${{secrets.DOCKER_HUB_PUBLISH_SECRETS}}
          docker login ${{ env.REGISTRY }}/linuxsuren --username linuxsuren --password ${{secrets.GH_PUBLISH_SECRETS}}
      - name: Upload via oras
        run: |
          export TAG=${{ steps.vars.outputs.tag }}
          tar czvf atest-data-swagger.tar.gz data
          oras push ${{ env.REGISTRY_DOCKERHUB }}/linuxsuren/atest-ext-data-swagger:${TAG#v} atest-data-swagger.tar.gz
          oras push ${{ env.REGISTRY }}/linuxsuren/atest-ext-data-swagger:${TAG#v} atest-data-swagger.tar.gz
